[package]
name = "mize_module_Blob"
version = "0.1.0"
edition = "2021"

[dependencies]
mize = { git = "https://github.com/c2vi/mize.git" }
tracing = "0.1.40"

[lib]
crate-type = ["cdylib", "rlib", "staticlib"]
